repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=5120']
    -   id: check-xml
    -   id: check-toml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.29.0
    hooks:
    -   id: commitizen
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.8
      args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ["--max-line-length=88"]